import Image from 'next/image'

import img1 from '../../../public/1.jpg'
import img2 from '../../../public/2.jpg'
import img3 from '../../../public/3.jpg'
import img4 from '../../../public/4.jpg'
import img5 from '../../../public/5.jpg'
import img6 from '../../../public/6.jpg'
import img7 from '../../../public/7.jpg'

export default function SignupsUser() {
    return (
        <div className='flex flex-wrap justify-center items-center text-justify'>
            <div className='relative z-30 cursor-pointer transition duration-300 hover:before:content-["Jani_Popovich"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl'>
                <Image src={img1} className='w-full h-full rounded-full' />
            </div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Rosina_Lamont"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>R</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Wava_Vermeulen"] before:w-32 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>W</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Delisa_Sheilds"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>
                <Image src={img2} className='w-full h-full rounded-full' />
            </div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Elsy_Wilhoit"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>
                <Image src={img3} className='w-full h-full rounded-full' />
            </div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Deanne_Jeffreys"] before:w-32 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>D</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["ddsds"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>F</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Shery_Heredia"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>S</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Gaylord_Coolbaugh"] before:w-36 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>G</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Lyda_Xortman"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>L</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Corene_Langstaff"] before:w-32 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>
                <Image src={img4} className='w-full h-full rounded-full' />
            </div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Matilda_Weibel"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>M</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Clement_Mayor"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>C</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Phil_Wyatt"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>P</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Altagracia_Manke"] before:w-32 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>A</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Siu_Derosier"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>S</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Aracely_Goudeau"] before:w-32 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>
                <Image src={img5} className='w-full h-full rounded-full' />
            </div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Bossman"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>B</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Crystal_Markel"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>C</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Noman_Nottage"] before:w-32 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>N</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Nigel_Shipe"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>
                <Image src={img6} className='w-full h-full rounded-full' />
            </div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Shaneka_Hoyle"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>S</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Milaro_Evans"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>M</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Vida_Serita"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>V</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Helopa_Menrta"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>H</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Tojiga_Dirtsa"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>T</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Fiona_Miona"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40'>F</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Azita_Bera"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>A</div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Melonie_Carreira"] before:w-32 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>
                <Image src={img7} className='w-full h-full rounded-full' />
            </div>
            <div className='w-10 h-10 xl:w-11 xl:h-11 rounded-full m-1 flex justify-center items-center text-[#dcf3ff] bg-[#394e5a] leading-9 text-xl relative z-30 cursor-pointer transition duration-300 hover:before:content-["Elinor_Enzdera"] before:w-28 before:h-fit hover:before:p-2 before:text-sm before:bg-white before:absolute before:top-0 before:left-0 before:-translate-y-10 before:-translate-x-5 before:rounded before:text-[#36576b] before:z-40 before:text-center '>E</div>
        </div>
    )
}